version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-db
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  java_app:
    image: openjdk:23
    container_name: java-app
    # Add your configurations here for your Java application
    # For example, you might mount your application code as a volume
    # volumes:
    #   - ./path/to/your/application:/app
    # command: ["java", "-jar", "your_application.jar"]
    depends_on:
      - postgres

volumes:
  postgres_data:
