version: '3.8'

services:
  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: all-in-one
    ports:
      - "5432:5432"
    networks:
      - appnetwork
    volumes:
      - db-data:/var/lib/postgresql/data

  java-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
    ports:
      - "8080:8080"
    environment:
      DB_HOST: jdbc:postgresql://postgresdb:5432/all-in-one
      DB_USERNAME: user
      DB_PASSWORD: secret
      BASE_PATH: /workspace/photo
    volumes:
      - upload:/workspace/photo
    networks:
      - appnetwork
    user: root:root

volumes:
  db-data:
  upload:

networks:
  appnetwork:
    driver: bridge
