
spring:
  application:
    name: @project.name@
    album:
      storage:
        local:
          path: ${BASE_PATH:/tmp/upload}
      thumbnail: false
  reactor:
    context-propagation: auto
  datasource:
    username: ${DB_USERNAME:fake}
    password: ${DB_PASSWORD:fake}
    url: ${DB_HOST:jdbc:postgresql://localhost:5740/database}
